In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
df1 = DataFrame({"key": ["b", "b", "a", "c", "a", "a", "b"],
                "data1": range(7)})

In [4]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [5]:
df2 = DataFrame({"key": ["a", "b", "d"],
                "data2": range(3)})

In [6]:
df2

data2 key
0      0   a
1      1   b
2      2   d

In [7]:
pd.merge(df1, df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [8]:
pd.merge(df1, df2, on = "key")

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [9]:
df3 = DataFrame({"lkey": ["b", "b", "a", "c", "a", "a", "b"],
                "data1": range(7)})

In [10]:
df3

data1 lkey
0      0    b
1      1    b
2      2    a
3      3    c
4      4    a
5      5    a
6      6    b

In [11]:
df4 = DataFrame({"rkey": ["a", "b", "d"],
                "data2": range(3)})

In [12]:
df4

data2 rkey
0      0    a
1      1    b
2      2    d

In [13]:
pd.merge(df3, df4, left_on = "lkey", right_on = "rkey")

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [14]:
pd.merge(df1, df2, how = "outer")

data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0

In [15]:
df1 = DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                "data1": range(6)})

In [16]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [17]:
df2 = DataFrame({"key": ["a", "b", "a", "b", "d"],
                "data2": range(5)})

In [18]:
df2

data2 key
0      0   a
1      1   b
2      2   a
3      3   b
4      4   d

In [19]:
pd.merge(df1, df2, on="key", how="left")

data1 key  data2
0       0   b    1.0
1       0   b    3.0
2       1   b    1.0
3       1   b    3.0
4       2   a    0.0
5       2   a    2.0
6       3   c    NaN
7       4   a    0.0
8       4   a    2.0
9       5   b    1.0
10      5   b    3.0

In [20]:
pd.merge(df1, df2, how="inner")

data1 key  data2
0      0   b      1
1      0   b      3
2      1   b      1
3      1   b      3
4      5   b      1
5      5   b      3
6      2   a      0
7      2   a      2
8      4   a      0
9      4   a      2

In [21]:
left = DataFrame({"key1": ["foo", "foo", "bar"],
                 "key2": ["one", "two", "one"],
                 "lval": [1, 2, 3]})

In [22]:
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [23]:
right = DataFrame({"key1": ["foo", "foo", "bar", "bar"],
                  "key2": ["one", "one", "one", "two"],
                  "rval": [4, 5, 6, 7]})

In [24]:
right

key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [25]:
pd.merge(left, right, on=["key1", "key2"], how="outer")

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [26]:
pd.merge(left, right, on="key1")

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [27]:
pd.merge(left, right, on="key1", suffixes=("_left", "_right"))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [28]:
left1 = DataFrame({"key": ["a", "b", "a", "a", "b", "c"],
                  "value": range(6)})

In [29]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [30]:
right1 = DataFrame({"group_val": [3.5, 7]}, index = ["a", "b"])

In [31]:
right1

group_val
a        3.5
b        7.0

In [32]:
pd.merge(left1, right1, left_on="key", right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [33]:
pd.merge(left1, right1, left_on="key", right_index=True, how="outer")

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [34]:
lefth = DataFrame({"key1": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada"],
                  "key2": [2000, 2001, 2002, 2001, 2002],
                  "data": np.arange(5.)})

In [35]:
lefth

data    key1  key2
0   0.0    Ohio  2000
1   1.0    Ohio  2001
2   2.0    Ohio  2002
3   3.0  Nevada  2001
4   4.0  Nevada  2002

In [36]:
righth = DataFrame(np.arange(12).reshape((6, 2)),
                  index = [["Nevada", "Nevada", "Ohio", "Ohio", "Ohio", "Ohio"],
                          [2001, 2000, 2000, 2000, 2001, 2002]],
                          columns = ["event1", "event2"])

In [37]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [38]:
pd.merge(lefth, righth, left_on=["key1", "key2"], right_index=True)

data    key1  key2  event1  event2
0   0.0    Ohio  2000       4       5
0   0.0    Ohio  2000       6       7
1   1.0    Ohio  2001       8       9
2   2.0    Ohio  2002      10      11
3   3.0  Nevada  2001       0       1

In [39]:
pd.merge(lefth, righth, left_on=["key1", "key2"],
        right_index=True, how="outer")

data    key1  key2  event1  event2
0   0.0    Ohio  2000     4.0     5.0
0   0.0    Ohio  2000     6.0     7.0
1   1.0    Ohio  2001     8.0     9.0
2   2.0    Ohio  2002    10.0    11.0
3   3.0  Nevada  2001     0.0     1.0
4   4.0  Nevada  2002     NaN     NaN
4   NaN  Nevada  2000     2.0     3.0

In [40]:
left2 = DataFrame([[1., 2.], [3., 4.], [5., 6.]], index=["a", "c", "e"],
                 columns = ["Ohio", "Nevada"])

In [41]:
left2

Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [42]:
right2 = DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                  index = ["b", "c", "d", "e"], columns = ["Missouri", "Alabama"])

In [43]:
right2

Missouri  Alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [44]:
pd.merge(left2, right2, how="outer", left_index=True, right_index=True)

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [45]:
left2.join(right2, how="outer")

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [46]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [47]:
right1

group_val
a        3.5
b        7.0

In [48]:
left1.join(right1, on="key")

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [49]:
another = DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
                   index = ["a", "c", "e", "f"], columns = ["New York", "Oregon"])

In [50]:
another

New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [51]:
left2

Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [52]:
right2

Missouri  Alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [53]:
left2.join([right2, another])

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0

In [54]:
left2.join([right2, another], how="outer")

c:\python27\lib\site-packages\pandas\core\frame.py:6369: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  verify_integrity=True)


Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
b   NaN     NaN       7.0      8.0       NaN     NaN
c   3.0     4.0       9.0     10.0       9.0    10.0
d   NaN     NaN      11.0     12.0       NaN     NaN
e   5.0     6.0      13.0     14.0      11.0    12.0
f   NaN     NaN       NaN      NaN      16.0    17.0

In [55]:
arr = np.arange(12).reshape((3, 4))

In [56]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [58]:
s1 = Series([0, 1], index=["a", "b"])

In [59]:
s1

a    0
b    1
dtype: int64

In [60]:
s2 = Series([2, 3, 4], index=["c", "d", "e"])

In [61]:
s2

c    2
d    3
e    4
dtype: int64

In [62]:
s3 = Series([5, 6], index=["f", "g"])

In [63]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [64]:
pd.concat([s1, s2, s3], axis=1)

c:\python27\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [65]:
s4 = pd.concat([s1 * 5, s3])

In [66]:
s4

a    0
b    5
f    5
g    6
dtype: int64

In [67]:
pd.concat([s1, s4], axis=1)

c:\python27\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

In [68]:
pd.concat([s1, s4], axis=1, join='inner')

0  1
a  0  0
b  1  5

In [69]:
pd.concat([s1, s4], axis=1, join_axes=[["a", "c", "b", "e"]])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  5.0
e  NaN  NaN

In [70]:
result = pd.concat([s1, s1, s3], keys=["one", "two", "three"])

In [71]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [72]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [73]:
pd.concat([s1, s2, s3], axis=1, keys=["one", "two", "three"])

c:\python27\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [74]:
df1 = DataFrame(np.arange(6).reshape(3, 2), index=["a", "b", "c"],
               columns=["one", "two"])

In [75]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [76]:
df2 = DataFrame(5 + np.arange(4).reshape(2, 2), index=["a", "c"],
               columns=["three", "four"])

In [77]:
df2

three  four
a      5     6
c      7     8

In [78]:
pd.concat([df1, df2], axis=1, keys=["level1", "level2"])

c:\python27\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [79]:
pd.concat({"level1": df1, "level2": df2}, axis=1)

c:\python27\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [80]:
pd.concat([df1, df2], axis=1, keys=["level1", "level2"],
         names=["upper", "lower"])

c:\python27\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [81]:
df1 = DataFrame(np.random.randn(3, 4), columns = ["a", "b", "c", "d"])

In [82]:
df1

a         b         c         d
0  1.545898 -2.164035  0.446819  0.493345
1 -0.766337 -1.797117  0.287869  0.018034
2 -0.256848 -0.471778 -0.107537 -0.186540

In [83]:
df2 = DataFrame(np.random.randn(2, 3), columns = ["b", "d", "a"])

In [84]:
df2

b         d         a
0  1.726641  0.076441  0.446597
1 -0.319160  0.345242 -1.774857

In [85]:
pd.concat([df1, df2], ignore_index = True)

c:\python27\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


a         b         c         d
0  1.545898 -2.164035  0.446819  0.493345
1 -0.766337 -1.797117  0.287869  0.018034
2 -0.256848 -0.471778 -0.107537 -0.186540
3  0.446597  1.726641       NaN  0.076441
4 -1.774857 -0.319160       NaN  0.345242

In [86]:
a = Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
          index = ["f", "e", "d", "c", "b", "a"])

In [87]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [88]:
b = Series(np.arange(len(a), dtype = np.float64),
          index = ["f", "e", "d", "c", "b", "a"])

In [89]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64

In [90]:
b[-1] = np.nan

In [91]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [92]:
np.where(pd.isnull(a), b, a)

array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [93]:
b[:-2]

f    0.0
e    1.0
d    2.0
c    3.0
dtype: float64

In [94]:
a[2:]

d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [95]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [96]:
df1 = DataFrame({"a": [1., np.nan, 5., np.nan],
                "b": [np.nan, 2., np.nan, 6.],
                "c": range(2, 18, 4)})

In [97]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [98]:
df2 = DataFrame({"a": [5., 4., np.nan, 3., 7.],
                "b": [np.nan, 3., 4., 6., 8.]})

In [99]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [100]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [101]:
data = DataFrame(np.arange(6).reshape((2, 3)),
                index = pd.Index(["Ohio", "Colorado"], name = "state"),
                columns = pd.Index(["one", "two", "three"], name = "number"))

In [102]:
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [103]:
result = data.stack()

In [104]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [105]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [106]:
result.unstack(0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [107]:
result.unstack("state")

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [108]:
s1 = Series([0, 1, 2, 3], index=["a", "b", "c", "d"])

In [109]:
s1

a    0
b    1
c    2
d    3
dtype: int64

In [110]:
s2 = Series([4, 5, 6], index = ["c", "d", "e"])

In [111]:
s2

c    4
d    5
e    6
dtype: int64

In [112]:
data2 = pd.concat([s1, s2], keys = ["one", "two"])

In [113]:
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [114]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [115]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [116]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

In [117]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [118]:
df = DataFrame({"left": result, "right": result + 5},
              columns = pd.Index(["left", "right"], name = "side"))

In [119]:
df

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [120]:
df.unstack("state")

side   left          right         
state  Ohio Colorado  Ohio Colorado
number                             
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [121]:
df.unstack("state").stack("side")

state         Colorado  Ohio
number side                 
one    left          3     0
       right         8     5
two    left          4     1
       right         9     6
three  left          5     2
       right        10     7

In [122]:
data = DataFrame({"k1": ["one"] * 3 + ["two"] * 4,
                 "k2": [1, 1, 2, 3, 3, 4, 4]})

In [123]:
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [124]:
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [125]:
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [126]:
data["v1"] = range(7)

In [127]:
data

k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6

In [128]:
data.drop_duplicates(["k1"])

k1  k2  v1
0  one   1   0
3  two   3   3

In [129]:
data.drop_duplicates(["k1", "k2"])

k1  k2  v1
0  one   1   0
2  one   2   2
3  two   3   3
5  two   4   5

In [132]:
data = DataFrame({"food": ["bacon", "pulled pork", "bacon", "Pastrami",
                          "corned beef", "Bacon", "pastrami", "honey ham",
                          "nova lox"],
                 "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [133]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [134]:
meat_to_animal = {"bacon": "pig",
                 "pulled pork": "pig",
                 "pastrami": "cow",
                 "corned beef": "cow",
                 "honey ham": "pig",
                 "nova lox": "salmon"}

In [135]:
meat_to_animal

{'bacon': 'pig',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon',
 'pastrami': 'cow',
 'pulled pork': 'pig'}

In [139]:
data["animal"] = data["food"].map(str.lower).map(meat_to_animal)

In [140]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [141]:
data["food"].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [142]:
data = Series([1., -999., 2., -999., -1000., 3.])

In [143]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [144]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [145]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [146]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [147]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [148]:
data = DataFrame(np.arange(12).reshape((3, 4)),
                index = ["Ohio", "Colorado", "New York"],
                columns = ["one", "two", "three", "four"])

In [149]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [150]:
data.index.map(str.upper)

Index([u'OHIO', u'COLORADO', u'NEW YORK'], dtype='object')

In [151]:
data.index = data.index.map(str.upper)

In [152]:
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [153]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [154]:
data.rename(index={"OHIO": "INDIANA"},
           columns = {"three": "peekaboo"})

one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

In [155]:
_ = data.rename(index={"OHIO": "INDIANA"}, inplace=True)

In [156]:
data

one  two  three  four
INDIANA     0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [157]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [158]:
ages

[20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [159]:
bins = [18, 25, 35, 60, 100]

In [160]:
cats = pd.cut(ages, bins)

In [161]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [164]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [165]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [166]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [167]:
bins

[18, 25, 35, 60, 100]

In [169]:
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [170]:
data = np.random.rand(20)

In [171]:
data

array([0.57778272, 0.25361483, 0.53804562, 0.28623049, 0.70895871,
       0.73623242, 0.24555085, 0.48518934, 0.43592023, 0.50148173,
       0.08276876, 0.09308738, 0.41156617, 0.44950113, 0.87358944,
       0.85080593, 0.53482054, 0.33896579, 0.76472569, 0.8434334 ])

In [172]:
pd.cut(data, 4, precision=2)

[(0.48, 0.68], (0.082, 0.28], (0.48, 0.68], (0.28, 0.48], (0.68, 0.87], ..., (0.68, 0.87], (0.48, 0.68], (0.28, 0.48], (0.68, 0.87], (0.68, 0.87]]
Length: 20
Categories (4, interval[float64]): [(0.082, 0.28] < (0.28, 0.48] < (0.48, 0.68] < (0.68, 0.87]]

In [173]:
data = np.random.randn(1000)

In [174]:
data

array([ 3.63262935e-01, -9.58015704e-01,  2.50969643e-01, -1.75669716e+00,
        6.76683094e-01,  1.20153519e-01,  5.73338734e-01, -5.57963896e-01,
        5.96326587e-01,  5.02328546e-01, -1.75728458e+00, -8.71787344e-02,
       -1.69071344e+00,  4.49014596e-01,  3.31853668e-03,  6.10385249e-01,
       -1.17689297e+00,  9.66830667e-01, -4.16044948e-01,  1.78350660e+00,
       -4.79419182e-01,  5.99478710e-01, -3.40361164e-01,  2.11026784e-01,
       -3.87056185e-01, -1.15823636e-01, -1.32492926e+00,  1.24661725e-01,
        5.53543735e-01, -1.04636454e+00, -2.01489697e-01, -7.65792211e-01,
        3.55405534e-01, -4.29085209e-01,  6.23213746e-01,  1.03338651e+00,
       -1.97969709e-01, -1.90987067e+00,  8.20476589e-02, -1.11206234e+00,
        3.88206746e-01,  1.08530348e+00,  1.15679205e-01, -1.90847680e-01,
       -2.41145583e-01, -6.75006716e-01,  1.56806171e+00,  1.15190739e+00,
        1.41463570e-01,  1.12616987e+00, -1.09070205e+00,  1.47484309e-01,
        7.53818087e-01,  

In [175]:
cats = pd.qcut(data, 4)   # Cut into quartiles

In [176]:
cats

[(0.0312, 0.63], (-3.661, -0.607], (0.0312, 0.63], (-3.661, -0.607], (0.63, 3.817], ..., (0.0312, 0.63], (-3.661, -0.607], (-3.661, -0.607], (0.0312, 0.63], (0.63, 3.817]]
Length: 1000
Categories (4, interval[float64]): [(-3.661, -0.607] < (-0.607, 0.0312] < (0.0312, 0.63] < (0.63, 3.817]]

In [177]:
pd.value_counts(cats)

(0.63, 3.817]       250
(0.0312, 0.63]      250
(-0.607, 0.0312]    250
(-3.661, -0.607]    250
dtype: int64

In [178]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(0.0312, 1.218], (-1.167, 0.0312], (0.0312, 1.218], (-3.661, -1.167], (0.0312, 1.218], ..., (0.0312, 1.218], (-1.167, 0.0312], (-1.167, 0.0312], (0.0312, 1.218], (0.0312, 1.218]]
Length: 1000
Categories (4, interval[float64]): [(-3.661, -1.167] < (-1.167, 0.0312] < (0.0312, 1.218] < (1.218, 3.817]]

In [179]:
np.random.seed(12345)

In [181]:
data = DataFrame(np.random.randn(1000, 4))

In [182]:
data

0         1         2         3
0   -0.204708  0.478943 -0.519439 -0.555730
1    1.965781  1.393406  0.092908  0.281746
2    0.769023  1.246435  1.007189 -1.296221
3    0.274992  0.228913  1.352917  0.886429
4   -2.001637 -0.371843  1.669025 -0.438570
5   -0.539741  0.476985  3.248944 -1.021228
6   -0.577087  0.124121  0.302614  0.523772
7    0.000940  1.343810 -0.713544 -0.831154
8   -2.370232 -1.860761 -0.860757  0.560145
9   -1.265934  0.119827 -1.063512  0.332883
10  -2.359419 -0.199543 -1.541996 -0.970736
11  -1.307030  0.286350  0.377984 -0.753887
12   0.331286  1.349742  0.069877  0.246674
13  -0.011862  1.004812  1.327195 -0.919262
14  -1.549106  0.022185  0.758363 -0.660524
15   0.862580 -0.010032  0.050009  0.670216
16   0.852965 -0.955869 -0.023493 -2.304234
17  -0.652469 -1.218302 -1.332610  1.074623
18   0.723642  0.690002  1.001543 -0.503087
19  -0.622274 -0.921169 -0.726213  0.222896
20   0.051316 -1.157719  0.816707  0.433610
21   1.010737  1.824875 -0.997518  0.850591
22  -0.131578  0.912414  0.188211  2.169461
23  -0.114928  2.003697  0.029610  0.795253
24   0.118110 -0.748532  0.584970  0.152677
25  -1.565657 -0.562540 -0.032664 -0.929006
26  -0.482573 -0.036264  1.095390  0.980928
27  -0.589488  1.581700 -0.528735  0.457002
28   0.929969 -1.569271 -1.022487 -0.402827
29   0.220487 -0.193401  0.669158 -1.648985
..        ...       ...       ...       ...
970  1.140886  0.113279  0.206782 -1.460094
971 -1.523554 -0.590572 -0.324064  0.132262
972  0.097878  1.244456 -0.048534 -1.091849
973 -0.738296  0.115881  0.016253 -1.243078
974 -1.969172 -1.141360  0.405558 -0.521155
975 -0.813280 -0.461413  1.159668 -0.307670
976  0.669147  0.397355  0.612537  1.381155
977 -0.042541  1.182125  0.153036  0.075798
978  0.615651 -1.992291  0.963044  0.102469
979  0.359400  0.355787 -0.799366  1.120895
980 -0.261844 -0.474138 -0.112021 -0.285176
981 -0.136429  1.285628  0.753586  0.053410
982 -0.355393  0.790731  1.274794  0.233619
983 -1.316005  1.396082  0.336700  0.604880
984  0.675317 -0.060329  1.801953 -0.335099
985 -0.754114  0.650691  0.365401  1.367213
986 -0.105654 -0.001860  0.316802 -0.512542
987 -0.052736 -0.457225  2.452835 -1.050942
988 -0.172078  0.853049 -0.356263 -0.387002
989  0.881601  1.067288  1.079688  1.642339
990 -0.103672 -0.882949 -0.197357  1.336648
991  0.926782 -0.527103  0.633763  0.153988
992 -0.527754  0.815104 -0.677870 -1.466596
993  0.957144  0.377342 -0.383241  1.101972
994  1.221058 -0.326481  0.750008  0.604072
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

[1000 rows x 4 columns]

In [183]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [184]:
col = data[3]

In [185]:
col

0     -0.555730
1      0.281746
2     -1.296221
3      0.886429
4     -0.438570
5     -1.021228
6      0.523772
7     -0.831154
8      0.560145
9      0.332883
10    -0.970736
11    -0.753887
12     0.246674
13    -0.919262
14    -0.660524
15     0.670216
16    -2.304234
17     1.074623
18    -0.503087
19     0.222896
20     0.433610
21     0.850591
22     2.169461
23     0.795253
24     0.152677
25    -0.929006
26     0.980928
27     0.457002
28    -0.402827
29    -1.648985
         ...   
970   -1.460094
971    0.132262
972   -1.091849
973   -1.243078
974   -0.521155
975   -0.307670
976    1.381155
977    0.075798
978    0.102469
979    1.120895
980   -0.285176
981    0.053410
982    0.233619
983    0.604880
984   -0.335099
985    1.367213
986   -0.512542
987   -1.050942
988   -0.387002
989    1.642339
990    1.336648
991    0.153988
992   -1.466596
993    1.101972
994    0.604072
995    1.653126
996   -1.502870
997    0.133304
998   -0.303340
999    0.882755
Name: 3, Length: 1000, d

In [190]:
col[np.abs(col) > 3]

97     3.927528
305   -3.399312
400   -3.745356
Name: 3, dtype: float64

In [192]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [194]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

In [195]:
df = DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [196]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [197]:
sampler = np.random.permutation(5)

In [198]:
sampler

array([1, 0, 2, 3, 4])

In [199]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [204]:
df.take(np.random.permutation(len(df))[:3])

0   1   2   3
0   0   1   2   3
3  12  13  14  15
2   8   9  10  11

In [205]:
bag = np.array([5, 7, -1, 6, 4])

In [206]:
bag

array([ 5,  7, -1,  6,  4])

In [207]:
sampler = np.random.randint(0, len(bag), size=10)

In [208]:
sampler

array([3, 0, 1, 2, 2, 3, 2, 1, 2, 0])

In [209]:
draws = bag.take(sampler)

In [210]:
draws

array([ 6,  5,  7, -1, -1,  6, -1,  7, -1,  5])

In [211]:
df = DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
               "data1": range(6)})

In [212]:
df

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [213]:
pd.get_dummies(df["key"])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [214]:
dummies = pd.get_dummies(df["key"], prefix="key")

In [215]:
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [218]:
df_with_dummy = df[["data1"]].join(dummies)

In [219]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [221]:
val = "a, b,   guido"

In [222]:
val.split(",")

['a', ' b', '   guido']

In [223]:
pieces = [x.strip() for x in val.split(",")]

In [224]:
pieces

['a', 'b', 'guido']

In [227]:
first, second, third = pieces

In [228]:
first + "::" + second + "::" + third

'a::b::guido'

In [229]:
"::".join(pieces)

'a::b::guido'

In [230]:
"guido" in val

True

In [231]:
val

'a, b,   guido'

In [232]:
val.index(",")

1

In [233]:
val.find(":")

-1

In [234]:
val.count(",")

2

In [235]:
val.replace(",", "::")

'a:: b::   guido'

In [236]:
val.replace(",", "")

'a b   guido'

In [237]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
       "Rob": "rob@gmail.com", "Wes": np.nan}

In [238]:
data

{'Dave': 'dave@google.com',
 'Rob': 'rob@gmail.com',
 'Steve': 'steve@gmail.com',
 'Wes': nan}

In [239]:
data = Series(data)

In [240]:
data

Dave     dave@google.com
Rob        rob@gmail.com
Steve    steve@gmail.com
Wes                  NaN
dtype: object

In [241]:
data.isnull()

Dave     False
Rob      False
Steve    False
Wes       True
dtype: bool

In [242]:
data.str.contains("gmail")

Dave     False
Rob       True
Steve     True
Wes        NaN
dtype: object